version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    healthcheck:      
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  node:
    build:
      context: ./node
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: appdb
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:      
      test: ["CMD", "curl", "-f", "http://mysql:3306"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: appdb      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  mysql_data: